# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'

target 'TuYou' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TuYou
  pod 'LeanCloud', '~> 15.0.0'
#  An IM App Framework, support sending text, pictures, audio, video, location
#  messaging, managing address book, more interesting features.
  pod 'ChatKit', '~> 2.3.11'
#  Harness the power of auto layout with a simplified, chainable, and compile
#  time safe syntax.
  pod 'SnapKit', '~> 4.2.0'
#  A clean and lightweight progress HUD for your iOS and tvOS app.
  pod 'SVProgressHUD', '~> 2.2.5'
#  A lightweight and pure Swift implemented library for downloading and cacheing
#  image from the web.
  pod 'Kingfisher', '~> 5.3.1'
end
