
platform :ios, '8.0'

target '毕业' do

pod 'AFNetworking'
pod 'PureLayout'
pod 'MJRefresh'
pod 'MJExtension'
pod 'SDWebImage'
pod 'Popover.OC'
pod 'TYAttributedLabel', '~> 2.6.2'
pod 'SMSSDK'
pod 'Masonry'
pod 'CLPlayer'
pod 'JKCountDownButton'

end
