# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

inhibit_all_warnings!

target 'JKSQ' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JKSQ
  # Offically supported JPush iOS SDK Pod. 官方支持的极光推送SDK.
   pod 'JPush', '~> 3.1.2-noidfa'
end
